In [2]:
import pandas as pd
import os

In [3]:
df_customers = pd.read_csv('../staging_1/customers/customers.csv')
df_stores = pd.read_csv('../staging_1/stores/stores.csv')

In [4]:
df_customers['local'] = df_customers['city'].isin(df_stores['city'])

# Print only rows where 'local' column is True
df_customers[df_customers['local']]

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,source,timestamp,local
67,68,Jayne,Kirkland,NaN,jayne.kirkland@hotmail.com,7800 Second Lane,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
78,79,Ashanti,Parks,NaN,ashanti.parks@hotmail.com,846 N. Helen St.,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
159,160,Omer,Estrada,NaN,omer.estrada@gmail.com,9 Honey Creek Street,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
193,194,Dorine,Roberson,NaN,dorine.roberson@msn.com,396 Meadowbrook Lane,Santa Cruz,CA,95060,datalake,2024-04-30 07:52:07.946855,True
313,314,Javier,Nichols,NaN,javier.nichols@msn.com,8944 Marconi St.,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
314,315,Justina,Jenkins,NaN,justina.jenkins@yahoo.com,8236 Creek St.,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
412,413,Ginette,Edwards,NaN,ginette.edwards@hotmail.com,9262 NW. Center Ave.,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
450,451,Jennette,Wooten,NaN,jennette.wooten@msn.com,8221 Bow Ridge Lane,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
472,473,Lashawna,Richardson,NaN,lashawna.richardson@hotmail.com,9920 Purple Finch St.,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
475,476,Christopher,Richardson,NaN,christopher.richardson@gmail.com,7846 Windfall Dr.,Santa Cruz,CA,95060,datalake,2024-04-30 07:52:07.946855,True
589,590,Cyndi,Dyer,NaN,cyndi.dyer@msn.com,313 West Argyle Ave.,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
656,657,Sam,Lester,NaN,sam.lester@gmail.com,563 South Beacon Lane,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
711,712,Kecia,Olsen,NaN,kecia.olsen@msn.com,8389 Central St.,Santa Cruz,CA,95060,datalake,2024-04-30 07:52:07.946855,True
807,808,Vallie,Dixon,NaN,vallie.dixon@yahoo.com,85 E. Ann Drive,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
849,850,Stephanie,Browning,NaN,stephanie.browning@yahoo.com,9156 Lantern St.,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
996,997,Trinidad,Mcclain,NaN,trinidad.mcclain@msn.com,98 Tunnel Drive,Baldwin,NY,11510,datalake,2024-04-30 07:52:07.946855,True
1028,1029,Ping,Quinn,NaN,ping.quinn@gmail.com,9051 Hanover Dr.,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
1063,1064,Patsy,Russo,NaN,patsy.russo@gmail.com,8438 Fairway Avenue,Rowlett,TX,75088,datalake,2024-04-30 07:52:07.946855,True
1414,1415,Harold,O'connor,NaN,harold.o'connor@gmail.com,9530 Summerhouse Street,Santa Cruz,CA,95060,datalake,2024-04-30 07:52:07.946855,True
1427,1428,Carola,Johns,NaN,carola.johns@msn.com,7077 Fordham Rd.,Santa Cruz,CA,95060,datalake,2024-04-30 07:52:07.946855,True

In [6]:
# Assuming 'name' contains the file name including the extension '.csv'
new_path = '../staging_2/'

# Expand '~' to the user's home directory
new_path = os.path.expanduser(new_path)

# Construct the folder path with the file name
folder_path = os.path.join(new_path, 'customers')

# Create the folder
os.makedirs(folder_path, exist_ok=True)

# Construct the file path within the newly created folder
file_path = os.path.join(folder_path, 'customers.csv')

# Save brands_df to the file_path
df_customers.to_csv(file_path, index=False)